<?php

/**
 * Implements hook_form_alter().
 */

function site_api_key_form_system_site_information_settings_alter(&$form, $form_state, $form_id)
{

    // Add Site API Key field to 'Site Information' section
    $site_api_key = \Drupal::config('siteapikey.configuration')->get('siteapikey');
    $form['site_information']['site_api_key'] = array(
        '#type' => 'textfield',
        '#title' => t('Site API Key'),
        '#default_value' => $site_api_key,
        '#description' => t('An API Key to access site pages in JSON format.'),
		'#class' => 'required',
		'#required' => 'required',
    );

    // Change form submit button text to 'Update Configuration'
    $form['actions']['submit']['#value'] = t('Update configuration');

    // Handle form submission
    $form['#submit'][] = 'site_api_key_handler';
}

function site_api_key_handler($form, &$form_state)
{
    // Update the system variable Site API Key
	$site_api = \Drupal::config('system.site')->get('siteapikey');
    $config = \Drupal::configFactory()->getEditable('siteapikey.configuration');
    $new_site_api_key = $form_state->getValue(['site_api_key']);
    $config->set('siteapikey', $new_site_api_key);
    $config->save();
	
	
	if(!empty($site_api)) {
			//Sets update message.
			if($site_api == 'No API Key yet'){
				$message = t($new_site_api_key.' is set as site API key.');
			}
			else{
				$message = t('Site API key is changed from '.$site_api.' to '.$new_site_api_key);
			}
			
		} else {
				//Sets success message.			
			$message = t($new_site_api_key.' is set as site API key.');
		}
		// Add message that Site API Key has been set
	\Drupal::messenger()->addStatus($message);
    
    
}
